inherit_from: .rubocop_todo.yml

AllCops:
  DisabledByDefault: true
  SuggestExtensions: false

require:
  - rubocop-packs

inherit_gem:
  rubocop-packs:
    - config/default.yml

Packs/DocumentedPublicApis:
  Enabled: true

Packs/TypedPublicApis:
  Enabled: true
