resources:
- name: generator-scripts-repo
  type: git
  source:
    uri: git@github.com:shageman/package-based-rails-applications-book.git
    branch: main
    depth: 1
    private_key: ((private_key))
  check_every: 10s




- name: empty-apps
  type: s3
  source:
    endpoint: http://minio:9000
    bucket: releases
    regexp: app_(.*)\.tgz
    access_key_id: minio
    secret_access_key: minio123
- name: c2s01-code
  type: s3
  source:
    endpoint: http://minio:9000
    bucket: releases
    regexp: c2s01-(.*)\.tgz
    access_key_id: minio
    secret_access_key: minio123
- name: c2s02-code
  type: s3
  source:
    endpoint: http://minio:9000
    bucket: releases
    regexp: c2s02-(.*)\.tgz
    access_key_id: minio
    secret_access_key: minio123
- name: c2s03-code
  type: s3
  source:
    endpoint: http://minio:9000
    bucket: releases
    regexp: c2s03-(.*)\.tgz
    access_key_id: minio
    secret_access_key: minio123
- name: c2s04-code
  type: s3
  source:
    endpoint: http://minio:9000
    bucket: releases
    regexp: c2s04-(.*)\.tgz
    access_key_id: minio
    secret_access_key: minio123
- name: c2s05-code
  type: s3
  source:
    endpoint: http://minio:9000
    bucket: releases
    regexp: c2s05-(.*)\.tgz
    access_key_id: minio
    secret_access_key: minio123
- name: c2s06-code
  type: s3
  source:
    endpoint: http://minio:9000
    bucket: releases
    regexp: c2s06-(.*)\.tgz
    access_key_id: minio
    secret_access_key: minio123
- name: c4s01-code
  type: s3
  source:
    endpoint: http://minio:9000
    bucket: releases
    regexp: c4s01-(.*)\.tgz
    access_key_id: minio
    secret_access_key: minio123
- name: c4s02-code
  type: s3
  source:
    endpoint: http://minio:9000
    bucket: releases
    regexp: c4s02-(.*)\.tgz
    access_key_id: minio
    secret_access_key: minio123
- name: c4s03-code
  type: s3
  source:
    endpoint: http://minio:9000
    bucket: releases
    regexp: c4s03-(.*)\.tgz
    access_key_id: minio
    secret_access_key: minio123
- name: c5s06-1-code
  type: s3
  source:
    endpoint: http://minio:9000
    bucket: releases
    regexp: c5s06-1-(.*)\.tgz
    access_key_id: minio
    secret_access_key: minio123
- name: c5s06-2-code
  type: s3
  source:
    endpoint: http://minio:9000
    bucket: releases
    regexp: c5s06-2-(.*)\.tgz
    access_key_id: minio
    secret_access_key: minio123
- name: c5s06-3-code
  type: s3
  source:
    endpoint: http://minio:9000
    bucket: releases
    regexp: c5s06-3-(.*)\.tgz
    access_key_id: minio
    secret_access_key: minio123
- name: c5s07-code
  type: s3
  source:
    endpoint: http://minio:9000
    bucket: releases
    regexp: c5s07-(.*)\.tgz
    access_key_id: minio
    secret_access_key: minio123




jobs:
- name: generate-empty-app
  serial_groups: [transform]
  plan:
  - get: generator-scripts-repo
  - task: generate-empty-app
    file: generator-scripts-repo/generator_scripts/ci/generate-code.yml
    output_mapping:
      code_output: empty-apps
  - put: empty-apps
    params:
      file: "empty-apps/*.tgz"
      acl: public-read




- name: c2s01
  serial_groups: [transform]
  plan:
  - get: generator-scripts-repo
  - get: empty-apps
  - task: c2s01-task
    file: generator-scripts-repo/generator_scripts/ci/transform-code.yml
    input_mapping:
      code_input: empty-apps
    output_mapping:
      code_output: c2s01-code
    params:
      PREV_CHAPTER: app
      CHAPTER: c2s01
  - put: c2s01-code
    params:
      file: "c2s01-code/c2s01-*.tgz"
      acl: public-read

- name: c2s01-test
  serial_groups: [test]
  plan:
  - get: generator-scripts-repo
  - get: c2s01-code
    passed: [c2s01]
    trigger: true
  - task: c2s01-test-task
    file: generator-scripts-repo/generator_scripts/ci/run-tests.yml
    input_mapping:
      app_code: c2s01-code
    params:
      CHAPTER: c2s01
      PACKWERK_CHECK: true




- name: c2s02
  serial_groups: [transform]
  plan:
  - get: generator-scripts-repo
  - get: c2s01-code
    passed: [c2s01]
    trigger: true
  - task: c2s02-task
    file: generator-scripts-repo/generator_scripts/ci/transform-code.yml
    input_mapping:
      code_input: c2s01-code
    output_mapping:
      code_output: c2s02-code
    params:
      PREV_CHAPTER: c2s01
      CHAPTER: c2s02
  - put: c2s02-code
    params:
      file: "c2s02-code/c2s02-*.tgz"
      acl: public-read

- name: c2s02-test
  serial_groups: [test]
  plan:
  - get: generator-scripts-repo
  - get: c2s02-code
    passed: [c2s02]
    trigger: true
  - task: c2s02-test-task
    file: generator-scripts-repo/generator_scripts/ci/run-tests.yml
    input_mapping:
      app_code: c2s02-code
    params:
      CHAPTER: c2s02
      PACKWERK_CHECK: true




- name: c2s03
  serial_groups: [transform]
  plan:
  - get: generator-scripts-repo
  - get: c2s02-code
    passed: [c2s02]
    trigger: true
  - task: c2s03-task
    file: generator-scripts-repo/generator_scripts/ci/transform-code.yml
    input_mapping:
      code_input: c2s02-code
    output_mapping:
      code_output: c2s03-code
    params:
      PREV_CHAPTER: c2s02
      CHAPTER: c2s03
  - put: c2s03-code
    params:
      file: "c2s03-code/c2s03-*.tgz"
      acl: public-read

- name: c2s03-test
  serial_groups: [test]
  plan:
  - get: generator-scripts-repo
  - get: c2s03-code
    passed: [c2s03]
    trigger: true
  - task: c2s03-test-task
    file: generator-scripts-repo/generator_scripts/ci/run-tests.yml
    input_mapping:
      app_code: c2s03-code
    params:
      CHAPTER: c2s03
      PACKWERK_CHECK: true



- name: c2s04
  serial_groups: [transform]
  plan:
  - get: generator-scripts-repo
  - get: c2s03-code
    passed: [c2s03]
    trigger: true
  - task: c2s04-task
    file: generator-scripts-repo/generator_scripts/ci/transform-code.yml
    input_mapping:
      code_input: c2s03-code
    output_mapping:
      code_output: c2s04-code
    params:
      PREV_CHAPTER: c2s03
      CHAPTER: c2s04
  - put: c2s04-code
    params:
      file: "c2s04-code/c2s04-*.tgz"
      acl: public-read

- name: c2s04-test
  serial_groups: [test]
  plan:
  - get: generator-scripts-repo
  - get: c2s04-code
    passed: [c2s04]
    trigger: true
  - task: c2s04-test-task
    file: generator-scripts-repo/generator_scripts/ci/run-tests.yml
    input_mapping:
      app_code: c2s04-code
    params:
      CHAPTER: c2s04
      PACKWERK_CHECK: true




- name: c2s05
  serial_groups: [transform]
  plan:
  - get: generator-scripts-repo
  - get: c2s04-code
    passed: [c2s04]
    trigger: true
  - task: c2s05-task
    file: generator-scripts-repo/generator_scripts/ci/transform-code.yml
    input_mapping:
      code_input: c2s04-code
    output_mapping:
      code_output: c2s05-code
    params:
      PREV_CHAPTER: c2s04
      CHAPTER: c2s05
  - put: c2s05-code
    params:
      file: "c2s05-code/c2s05-*.tgz"
      acl: public-read

- name: c2s05-test
  serial_groups: [test]
  plan:
  - get: generator-scripts-repo
  - get: c2s05-code
    passed: [c2s05]
    trigger: true
  - task: c2s05-test-task
    file: generator-scripts-repo/generator_scripts/ci/run-tests.yml
    input_mapping:
      app_code: c2s05-code
    params:
      CHAPTER: c2s05
      PACKWERK_CHECK: true




- name: c2s06
  serial_groups: [transform]
  plan:
  - get: generator-scripts-repo
  - get: c2s05-code
    passed: [c2s05]
    trigger: true
  - task: c2s06-task
    file: generator-scripts-repo/generator_scripts/ci/transform-code.yml
    input_mapping:
      code_input: c2s05-code
    output_mapping:
      code_output: c2s06-code
    params:
      PREV_CHAPTER: c2s05
      CHAPTER: c2s06
  - put: c2s06-code
    params:
      file: "c2s06-code/c2s06-*.tgz"
      acl: public-read

- name: c2s06-test
  serial_groups: [test]
  plan:
  - get: generator-scripts-repo
  - get: c2s06-code
    passed: [c2s06]
    trigger: true
  - task: c2s06-test-task
    file: generator-scripts-repo/generator_scripts/ci/run-tests.yml
    input_mapping:
      app_code: c2s06-code
    params:
      CHAPTER: c2s06
      PACKWERK_CHECK: true




- name: c4s01
  serial_groups: [transform]
  plan:
  - get: generator-scripts-repo
  - get: c2s06-code
    passed: [c2s06]
    trigger: true
  - task: c4s01-task
    file: generator-scripts-repo/generator_scripts/ci/transform-code.yml
    input_mapping:
      code_input: c2s06-code
    output_mapping:
      code_output: c4s01-code
    params:
      PREV_CHAPTER: c2s06
      CHAPTER: c4s01
  - put: c4s01-code
    params:
      file: "c4s01-code/c4s01-*.tgz"
      acl: public-read

- name: c4s01-test
  serial_groups: [test]
  plan:
  - get: generator-scripts-repo
  - get: c4s01-code
    passed: [c4s01]
    trigger: true
  - task: c4s01-test-task
    file: generator-scripts-repo/generator_scripts/ci/run-tests.yml
    input_mapping:
      app_code: c4s01-code
    params:
      CHAPTER: c4s01
      PACKWERK_CHECK: true




- name: c4s02
  serial_groups: [transform]
  plan:
  - get: generator-scripts-repo
  - get: c2s06-code
    passed: [c2s06]
    trigger: true
  - task: c4s02-task
    file: generator-scripts-repo/generator_scripts/ci/transform-code.yml
    input_mapping:
      code_input: c2s06-code
    output_mapping:
      code_output: c4s02-code
    params:
      PREV_CHAPTER: c2s06
      CHAPTER: c4s02
  - put: c4s02-code
    params:
      file: "c4s02-code/c4s02-*.tgz"
      acl: public-read

- name: c4s02-test
  serial_groups: [test]
  plan:
  - get: generator-scripts-repo
  - get: c4s02-code
    passed: [c4s02]
    trigger: true
  - task: c4s02-test-task
    file: generator-scripts-repo/generator_scripts/ci/run-tests.yml
    input_mapping:
      app_code: c4s02-code
    params:
      CHAPTER: c4s02
      PACKWERK_CHECK: true




- name: c4s03
  serial_groups: [transform]
  plan:
  - get: generator-scripts-repo
  - get: c2s06-code
    passed: [c2s06]
    trigger: true
  - task: c4s03-task
    file: generator-scripts-repo/generator_scripts/ci/transform-code.yml
    input_mapping:
      code_input: c2s06-code
    output_mapping:
      code_output: c4s03-code
    params:
      PREV_CHAPTER: c2s06
      CHAPTER: c4s03
  - put: c4s03-code
    params:
      file: "c4s03-code/c4s03-*.tgz"
      acl: public-read

- name: c4s03-test
  serial_groups: [test]
  plan:
  - get: generator-scripts-repo
  - get: c4s03-code
    passed: [c4s03]
    trigger: true
  - task: c4s03-test-task
    file: generator-scripts-repo/generator_scripts/ci/run-tests.yml
    input_mapping:
      app_code: c4s03-code
    params:
      CHAPTER: c4s03
      PACKWERK_CHECK: true




- name: c5s06-1
  serial_groups: [transform]
  plan:
  - get: generator-scripts-repo
  - get: c2s06-code
    passed: [c2s06]
    trigger: true
  - task: c5s06-1-task
    file: generator-scripts-repo/generator_scripts/ci/transform-code.yml
    input_mapping:
      code_input: c2s06-code
    output_mapping:
      code_output: c5s06-1-code
    params:
      PREV_CHAPTER: c2s06
      CHAPTER: c5s06-1
  - put: c5s06-1-code
    params:
      file: "c5s06-1-code/c5s06-1-*.tgz"
      acl: public-read

- name: c5s06-1-test
  serial_groups: [test]
  plan:
  - get: generator-scripts-repo
  - get: c5s06-1-code
    passed: [c5s06-1]
    trigger: true
  - task: c5s06-1-test-task
    file: generator-scripts-repo/generator_scripts/ci/run-tests.yml
    input_mapping:
      app_code: c5s06-1-code
    params:
      CHAPTER: c5s06-1
      PACKWERK_CHECK: true




- name: c5s06-2
  serial_groups: [transform]
  plan:
  - get: generator-scripts-repo
  - get: c5s06-1-code
    passed: [c5s06-1]
    trigger: true
  - task: c5s06-2-task
    file: generator-scripts-repo/generator_scripts/ci/transform-code.yml
    input_mapping:
      code_input: c5s06-1-code
    output_mapping:
      code_output: c5s06-2-code
    params:
      PREV_CHAPTER: c5s06-1
      CHAPTER: c5s06-2
  - put: c5s06-2-code
    params:
      file: "c5s06-2-code/c5s06-2-*.tgz"
      acl: public-read

- name: c5s06-2-test
  serial_groups: [test]
  plan:
  - get: generator-scripts-repo
  - get: c5s06-2-code
    passed: [c5s06-2]
    trigger: true
  - task: c5s06-2-test-task
    file: generator-scripts-repo/generator_scripts/ci/run-tests.yml
    input_mapping:
      app_code: c5s06-2-code
    params:
      CHAPTER: c5s06-2
      SORBET: true
      PACKWERK_CHECK: true




- name: c5s06-3
  serial_groups: [transform]
  plan:
  - get: generator-scripts-repo
  - get: c5s06-2-code
    passed: [c5s06-2]
    trigger: true
  - task: c5s06-3-task
    file: generator-scripts-repo/generator_scripts/ci/transform-code.yml
    input_mapping:
      code_input: c5s06-2-code
    output_mapping:
      code_output: c5s06-3-code
    params:
      PREV_CHAPTER: c5s06-2
      CHAPTER: c5s06-3
  - put: c5s06-3-code
    params:
      file: "c5s06-3-code/c5s06-3-*.tgz"
      acl: public-read

- name: c5s06-3-test
  serial_groups: [test]
  plan:
  - get: generator-scripts-repo
  - get: c5s06-3-code
    passed: [c5s06-3]
    trigger: true
  - task: c5s06-3-test-task
    file: generator-scripts-repo/generator_scripts/ci/run-tests.yml
    input_mapping:
      app_code: c5s06-3-code
    params:
      CHAPTER: c5s06-3
      SORBET: true
      PACKWERK_CHECK: true




- name: c5s07
  serial_groups: [transform]
  plan:
  - get: generator-scripts-repo
    trigger: false
  - get: c2s06-code
    passed: [c2s06]
    trigger: true
  - task: c5s07-task
    file: generator-scripts-repo/generator_scripts/ci/transform-code.yml
    input_mapping:
      code_input: c2s06-code
    output_mapping:
      code_output: c5s07-code
    params:
      PREV_CHAPTER: c2s06
      CHAPTER: c5s07
  - put: c5s07-code
    params:
      file: "c5s07-code/c5s07-*.tgz"
      acl: public-read

- name: c5s07-test
  serial_groups: [test]
  plan:
  - get: generator-scripts-repo
  - get: c5s07-code
    passed: [c5s07]
    trigger: true
  - task: c5s07-test-task
    file: generator-scripts-repo/generator_scripts/ci/run-tests.yml
    input_mapping:
      app_code: c5s07-code
    params:
      CHAPTER: c5s07
      PACKWERK_CHECK: true
