# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `no_proxy_fix` gem.
# Please instead update this file by running `bin/tapioca gem no_proxy_fix`.

# source://no_proxy_fix//lib/no_proxy_fix/version.rb#1
module NoProxyFix; end

# source://no_proxy_fix//lib/no_proxy_fix/version.rb#2
NoProxyFix::VERSION = T.let(T.unsafe(nil), String)
