# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/pocky/all/pocky.rbi
#
# pocky-62f4c64c9d8e

module Pocky
end
class Pocky::InvalidRootPathError < StandardError
end
class Pocky::Packwerk
  def build_directed_graph; end
  def dependencies_files; end
  def deprecated_references_files; end
  def draw_dependencies; end
  def draw_deprecated_references; end
  def edge_width(count); end
  def generate; end
  def initialize(package_path: nil, default_package: nil, filename: nil, dpi: nil, package_color: nil, dependency_edge: nil, deprecated_reference_edge: nil); end
  def load_dependencies; end
  def load_deprecated_references; end
  def package_name_for_dependency(name); end
  def parse_package_name(filename); end
  def self.generate(params); end
  def self.new(*arg0); end
end
class Pocky::Railtie < Rails::Railtie
end
