# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `visualize_packwerk` gem.
# Please instead update this file by running `bin/tapioca gem visualize_packwerk`.

# source://visualize_packwerk//lib/visualize_packwerk.rb#8
module VisualizePackwerk
  class << self
    # source://visualize_packwerk//lib/visualize_packwerk.rb#142
    def all_nested_packages(all_package_names); end

    # source://visualize_packwerk//lib/visualize_packwerk.rb#50
    def code_owner(package); end

    # source://visualize_packwerk//lib/visualize_packwerk.rb#54
    def diagram_title(options, max_violation_count); end

    # source://visualize_packwerk//lib/visualize_packwerk.rb#121
    def filtered(packwerk_packages, filter_package, filter_folder); end

    # source://visualize_packwerk//lib/visualize_packwerk.rb#103
    def max_violation_count(all_packages, show_edge); end

    # source://visualize_packwerk//lib/visualize_packwerk.rb#91
    def node_color_builder; end

    # @raise [ArgumentError]
    #
    # source://visualize_packwerk//lib/visualize_packwerk.rb#10
    def package_graph!(options, raw_config, packwerk_packages); end

    # source://visualize_packwerk//lib/visualize_packwerk.rb#156
    def remove_nested_packs(packages); end

    # source://visualize_packwerk//lib/visualize_packwerk.rb#75
    def show_edge_builder(options, all_package_names); end
  end
end
