# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `ruby-vips` gem.
# Please instead update this file by running `bin/tapioca gem ruby-vips`.

# source://ruby-vips//lib/vips.rb#36
module GLib
  extend ::FFI::Library

  class << self
    # Returns the value of attribute logger.
    #
    # source://ruby-vips//lib/vips.rb#38
    def logger; end

    # Sets the attribute logger
    #
    # @param value the value to set the attribute logger to.
    #
    # source://ruby-vips//lib/vips.rb#38
    def logger=(_arg0); end
  end
end

class Object < ::BasicObject
  include ::Kernel
  include ::PP::ObjectMixin

  private

  # source://ruby-vips//lib/vips.rb#26
  def library_name(name, abi_number); end
end
