inherit_from: ../../.rubocop.yml

Packs/ClassMethodsAsPublicApis:
  Enabled: false

Packs/RootNamespaceIsPackName:
  Enabled: false

Packs/TypedPublicApis:
  Enabled: false

Packs/DocumentedPublicApis:
  Enabled: false
