#!/bin/bash

set -v
set -x
set -e

mkdir -p app/packages/rails_shims/mailers/; mv app/mailers/application_mailer.rb $_
mkdir -p app/packages/rails_shims/models/; mv app/models/application_record.rb $_
mkdir -p app/packages/rails_shims/models/concerns/; mv app/models/concerns/.keep $_
mkdir -p app/packages/rails_shims/jobs/; mv app/jobs/application_job.rb $_
mkdir -p app/packages/rails_shims/controllers/; mv app/controllers/application_controller.rb $_
mkdir -p app/packages/rails_shims/controllers/concerns/; mv app/controllers/concerns/.keep $_
mkdir -p app/packages/rails_shims/helpers/; mv app/helpers/application_helper.rb $_
mkdir -p app/packages/rails_shims/channels/application_cable/; mv app/channels/application_cable/connection.rb $_
mkdir -p app/packages/rails_shims/channels/application_cable/; mv app/channels/application_cable/channel.rb $_

find . -type d -empty -delete

echo "enforce_dependencies: true
enforce_privacy: false" > app/packages/rails_shims/package.yml

echo '
enforce_dependencies: true
enforce_privacy: false
dependencies:
- app/packages/rails_shims
- app/packages/teams
' > app/packages/games/package.yml

echo '
enforce_dependencies: true
enforce_privacy: false
dependencies:
- app/packages/rails_shims
- app/packages/games
' > app/packages/games_admin/package.yml

echo '
enforce_dependencies: true
enforce_privacy: false
dependencies:
- app/packages/rails_shims
- app/packages/games
- app/packages/teams
- app/packages/predictor
' > app/packages/prediction_ui/package.yml

echo '
enforce_dependencies: true
enforce_privacy: false
dependencies:
- app/packages/rails_shims
' > app/packages/teams/package.yml

echo '
enforce_dependencies: true
enforce_privacy: false
dependencies:
- app/packages/rails_shims
- app/packages/teams
' > app/packages/teams_admin/package.yml

echo '
enforce_dependencies: true
enforce_privacy: false
dependencies:
- app/packages/rails_shims
' > app/packages/welcome_ui/package.yml

echo '# See: Setting up the configuration file
# https://github.com/Shopify/packwerk/blob/main/USAGE.md#setting-up-the-configuration-file

# List of patterns for folder paths to include
# include:
# - "**/*.{rb,rake,erb}"

# List of patterns for folder paths to exclude
exclude:
- "{bin,node_modules,script,tmp,vendor}/**/*"
- "vendor/bundle/**/*"
- "**/lib/tasks/**/*.rake"

# Patterns to find package configuration files
# package_paths: "**/"

# List of application load paths
# These load paths were auto generated by Packwerk.
load_paths:
- app/packages
- app/packages/games_admin/controllers
- app/packages/games_admin/package.yml
- app/packages/games_admin/views
- app/packages/games/models
- app/packages/games/package.yml
- app/packages/prediction_ui/controllers
- app/packages/prediction_ui/helpers
- app/packages/prediction_ui/package.yml
- app/packages/prediction_ui/views
- app/packages/predictor/models
- app/packages/predictor/package.yml
- app/packages/rails_shims/channels
- app/packages/rails_shims/controllers
- app/packages/rails_shims/controllers/concerns
- app/packages/rails_shims/helpers
- app/packages/rails_shims/jobs
- app/packages/rails_shims/mailers
- app/packages/rails_shims/models
- app/packages/rails_shims/models/concerns
- app/packages/rails_shims/package.yml
- app/packages/teams_admin/controllers
- app/packages/teams_admin/package.yml
- app/packages/teams_admin/views
- app/packages/teams/models
- app/packages/teams/package.yml
- app/packages/welcome_ui/controllers
- app/packages/welcome_ui/package.yml
- app/packages/welcome_ui/views

# List of custom associations, if any
# custom_associations:
# - "cache_belongs_to"

# Location of inflections file
# inflections_file: "config/inflections.yml"
' > packwerk.yml
