# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `colorize` gem.
# Please instead update this file by running `bin/tapioca gem colorize`.

# Gem version
#
# source://colorize//lib/colorize/errors.rb#3
module Colorize; end

# source://colorize//lib/colorize/class_methods.rb#4
module Colorize::ClassMethods
  # Add color alias
  #
  # source://colorize//lib/colorize/class_methods.rb#113
  def add_color_alias(*params); end

  # source://colorize//lib/colorize/class_methods.rb#132
  def add_color_code(code, color); end

  # Generate color and on_color method
  #
  # source://colorize//lib/colorize/class_methods.rb#157
  def add_color_method(key); end

  # Check if color exists
  #
  # source://colorize//lib/colorize/class_methods.rb#192
  def check_if_color_available!(color); end

  # Check if color is missing
  #
  # source://colorize//lib/colorize/class_methods.rb#199
  def check_if_color_exist!(color); end

  # Color codes hash
  #
  # source://colorize//lib/colorize/class_methods.rb#128
  def color_codes; end

  # @return [Boolean]
  #
  # source://colorize//lib/colorize/class_methods.rb#203
  def color_exist?(color); end

  # Generate color and on_color methods
  #
  # source://colorize//lib/colorize/class_methods.rb#146
  def color_methods; end

  # Display color samples
  #
  # source://colorize//lib/colorize/class_methods.rb#103
  def color_samples; end

  # Return array of available colors used by colorize
  #
  # source://colorize//lib/colorize/class_methods.rb#89
  def colors; end

  # Property for disable colorization
  #
  # source://colorize//lib/colorize/class_methods.rb#45
  def disable_colorization(value = T.unsafe(nil)); end

  # Setter for disable colorization
  #
  # source://colorize//lib/colorize/class_methods.rb#60
  def disable_colorization=(value); end

  # Mode codes hash
  #
  # source://colorize//lib/colorize/class_methods.rb#139
  def mode_codes; end

  # Return array of available modes used by colorize
  #
  # source://colorize//lib/colorize/class_methods.rb#96
  def modes; end

  # Generate modes methods
  #
  # source://colorize//lib/colorize/class_methods.rb#170
  def modes_methods; end

  # source://colorize//lib/colorize/class_methods.rb#180
  def parse_color_alias_params(params); end

  # Property for prevent recolorization
  #
  # source://colorize//lib/colorize/class_methods.rb#67
  def prevent_colors(value = T.unsafe(nil)); end

  # Setter for prevent recolorization
  #
  # source://colorize//lib/colorize/class_methods.rb#82
  def prevent_colors=(value); end
end

# source://colorize//lib/colorize/errors.rb#4
class Colorize::ColorAlreadyExist < ::StandardError; end

# source://colorize//lib/colorize/errors.rb#7
class Colorize::ColorDontExist < ::StandardError; end

# source://colorize//lib/colorize/instance_methods.rb#4
module Colorize::InstanceMethods
  # Change color of string
  #
  # Examples:
  #
  #   puts "This is blue".colorize(:blue)
  #   puts "This is light blue".colorize(:light_blue)
  #   puts "This is also blue".colorize(:color => :blue)
  #   puts "This is light blue with red background".colorize(:color => :light_blue, :background => :red)
  #   puts "This is light blue with red background".colorize(:light_blue ).colorize( :background => :red)
  #   puts "This is blue text on red".blue.on_red
  #   puts "This is red on blue".colorize(:red).on_blue
  #   puts "This is red on blue and underline".colorize(:red).on_blue.underline
  #   puts "This is blue text on red".blue.on_red.blink
  #   puts "This is uncolorized".blue.on_red.uncolorize
  #
  # source://colorize//lib/colorize/instance_methods.rb#21
  def colorize(params); end

  # Return true if string is colorized
  #
  # @return [Boolean]
  #
  # source://colorize//lib/colorize/instance_methods.rb#43
  def colorized?; end

  # Return uncolorized string
  #
  # source://colorize//lib/colorize/instance_methods.rb#34
  def uncolorize; end

  private

  # Color for background (offset 10)
  #
  # source://colorize//lib/colorize/instance_methods.rb#106
  def background_color(color); end

  # Color for foreground
  #
  # source://colorize//lib/colorize/instance_methods.rb#99
  def color(color); end

  # Set color from params symbol
  #
  # source://colorize//lib/colorize/instance_methods.rb#88
  def color_from_symbol(match, symbol); end

  # Set colors from params hash
  #
  # source://colorize//lib/colorize/instance_methods.rb#73
  def colors_from_hash(match, hash); end

  # Set color from params
  #
  # source://colorize//lib/colorize/instance_methods.rb#63
  def colors_from_params(match, params); end

  # Set default colors
  #
  # source://colorize//lib/colorize/instance_methods.rb#54
  def defaults_colors(match); end

  # Mode
  #
  # source://colorize//lib/colorize/instance_methods.rb#113
  def mode(mode); end

  # Require windows libs
  #
  # source://colorize//lib/colorize/instance_methods.rb#138
  def require_windows_libs; end

  # Scan for colorized string
  #
  # source://colorize//lib/colorize/instance_methods.rb#120
  def scan_for_colors; end

  # source://colorize//lib/colorize/instance_methods.rb#126
  def split_colors(match); end
end

# ColorizedString class extension.
#
# source://colorize//lib/colorized_string.rb#9
class ColorizedString < ::String
  include ::Colorize::InstanceMethods
  extend ::Colorize::ClassMethods

  # source://colorize//lib/colorize/class_methods.rb#158
  def black; end

  # source://colorize//lib/colorize/class_methods.rb#174
  def blink; end

  # source://colorize//lib/colorize/class_methods.rb#174
  def blink_fast; end

  # source://colorize//lib/colorize/class_methods.rb#174
  def blink_slow; end

  # source://colorize//lib/colorize/class_methods.rb#158
  def blue; end

  # source://colorize//lib/colorize/class_methods.rb#174
  def bold; end

  # source://colorize//lib/colorize/class_methods.rb#158
  def cyan; end

  # source://colorize//lib/colorize/class_methods.rb#174
  def dim; end

  # source://colorize//lib/colorize/class_methods.rb#174
  def double_underline; end

  # source://colorize//lib/colorize/class_methods.rb#158
  def gray; end

  # source://colorize//lib/colorize/class_methods.rb#158
  def green; end

  # source://colorize//lib/colorize/class_methods.rb#158
  def grey; end

  # source://colorize//lib/colorize/class_methods.rb#174
  def hide; end

  # source://colorize//lib/colorize/class_methods.rb#174
  def invert; end

  # source://colorize//lib/colorize/class_methods.rb#174
  def italic; end

  # source://colorize//lib/colorize/class_methods.rb#158
  def light_black; end

  # source://colorize//lib/colorize/class_methods.rb#158
  def light_blue; end

  # source://colorize//lib/colorize/class_methods.rb#158
  def light_cyan; end

  # source://colorize//lib/colorize/class_methods.rb#158
  def light_green; end

  # source://colorize//lib/colorize/class_methods.rb#158
  def light_magenta; end

  # source://colorize//lib/colorize/class_methods.rb#158
  def light_red; end

  # source://colorize//lib/colorize/class_methods.rb#158
  def light_white; end

  # source://colorize//lib/colorize/class_methods.rb#158
  def light_yellow; end

  # source://colorize//lib/colorize/class_methods.rb#158
  def magenta; end

  # source://colorize//lib/colorize/class_methods.rb#162
  def on_black; end

  # source://colorize//lib/colorize/class_methods.rb#162
  def on_blue; end

  # source://colorize//lib/colorize/class_methods.rb#162
  def on_cyan; end

  # source://colorize//lib/colorize/class_methods.rb#162
  def on_gray; end

  # source://colorize//lib/colorize/class_methods.rb#162
  def on_green; end

  # source://colorize//lib/colorize/class_methods.rb#162
  def on_grey; end

  # source://colorize//lib/colorize/class_methods.rb#162
  def on_light_black; end

  # source://colorize//lib/colorize/class_methods.rb#162
  def on_light_blue; end

  # source://colorize//lib/colorize/class_methods.rb#162
  def on_light_cyan; end

  # source://colorize//lib/colorize/class_methods.rb#162
  def on_light_green; end

  # source://colorize//lib/colorize/class_methods.rb#162
  def on_light_magenta; end

  # source://colorize//lib/colorize/class_methods.rb#162
  def on_light_red; end

  # source://colorize//lib/colorize/class_methods.rb#162
  def on_light_white; end

  # source://colorize//lib/colorize/class_methods.rb#162
  def on_light_yellow; end

  # source://colorize//lib/colorize/class_methods.rb#162
  def on_magenta; end

  # source://colorize//lib/colorize/class_methods.rb#162
  def on_red; end

  # source://colorize//lib/colorize/class_methods.rb#162
  def on_white; end

  # source://colorize//lib/colorize/class_methods.rb#162
  def on_yellow; end

  # source://colorize//lib/colorize/class_methods.rb#174
  def overlined; end

  # source://colorize//lib/colorize/class_methods.rb#158
  def red; end

  # source://colorize//lib/colorize/class_methods.rb#174
  def reveal; end

  # source://colorize//lib/colorize/class_methods.rb#174
  def strike; end

  # source://colorize//lib/colorize/class_methods.rb#174
  def underline; end

  # source://colorize//lib/colorize/class_methods.rb#158
  def white; end

  # source://colorize//lib/colorize/class_methods.rb#158
  def yellow; end

  class << self
    # Shortcut to create ColorizedString with ColorizedString['test'].
    #
    # source://colorize//lib/colorized_string.rb#22
    def [](string); end
  end
end
